# generated by datamodel-codegen:
#   filename:  ionforge-openapi.json
#   timestamp: 2026-04-03T14:53:41+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AwareDatetime, Field, confloat, conint, constr

from ionforge._types._base_model import ApiModel


class Project(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    created_by: str = Field(..., alias="createdBy")
    name: str
    description: str | None
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")


class ProjectWithCounts(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    created_by: str = Field(..., alias="createdBy")
    name: str
    description: str | None
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")
    simulation_count: int = Field(..., alias="simulationCount")
    geometry_count: int = Field(..., alias="geometryCount")


class GeometryMeta(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    created_by: str = Field(..., alias="createdBy")
    project_id: str = Field(..., alias="projectId")
    name: str
    description: str | None
    size_bytes: float = Field(..., alias="sizeBytes")
    vertex_count: int = Field(..., alias="vertexCount")
    face_count: int = Field(..., alias="faceCount")
    group_count: int = Field(..., alias="groupCount")
    thumbnail_url: str | None = Field(..., alias="thumbnailUrl")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")


class GeometryListItem(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    created_by: str = Field(..., alias="createdBy")
    name: str
    description: str | None
    thumbnail_url: str | None = Field(..., alias="thumbnailUrl")
    vertex_count: int = Field(..., alias="vertexCount")
    face_count: int = Field(..., alias="faceCount")
    group_count: int = Field(..., alias="groupCount")
    size_bytes: float = Field(..., alias="sizeBytes")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")


class Simulation(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    user_id: str = Field(..., alias="userId")
    project_id: str = Field(..., alias="projectId")
    name: str
    description: str | None
    simulator_type: str = Field(..., alias="simulatorType")
    geometry_id: str | None = Field(..., alias="geometryId")
    params: dict[str, Any]
    is_template: bool = Field(..., alias="isTemplate")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")


class LatestJobStatus(StrEnum):
    queued = "queued"
    running = "running"
    completed = "completed"
    failed = "failed"


class SimulationWithCounts(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    user_id: str = Field(..., alias="userId")
    project_id: str = Field(..., alias="projectId")
    name: str
    description: str | None
    simulator_type: str = Field(..., alias="simulatorType")
    geometry_id: str | None = Field(..., alias="geometryId")
    params: dict[str, Any]
    is_template: bool = Field(..., alias="isTemplate")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")
    job_count: int = Field(..., alias="jobCount")
    latest_job_status: LatestJobStatus | None = Field(..., alias="latestJobStatus")


class Status(StrEnum):
    queued = "queued"
    running = "running"
    completed = "completed"
    failed = "failed"


class Job(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    user_id: str = Field(..., alias="userId")
    simulation_id: str = Field(..., alias="simulationId")
    name: str
    status: Status
    simulator_type: str = Field(..., alias="simulatorType")
    geometry_id: str | None = Field(..., alias="geometryId")
    params: dict[str, Any]
    sweep_id: str | None = Field(..., alias="sweepId")
    sweep_point: dict[str, float] | None = Field(..., alias="sweepPoint")
    error_message: str | None = Field(..., alias="errorMessage")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    started_at: AwareDatetime | None = Field(..., alias="startedAt")
    completed_at: AwareDatetime | None = Field(..., alias="completedAt")


class Sweep(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    user_id: str = Field(..., alias="userId")
    simulation_id: str = Field(..., alias="simulationId")
    name: str
    status: str
    strategy: str
    parameter_space: dict[str, Any] = Field(..., alias="parameterSpace")
    total_points: int = Field(..., alias="totalPoints")
    completed_points: int = Field(..., alias="completedPoints")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    started_at: AwareDatetime | None = Field(..., alias="startedAt")
    completed_at: AwareDatetime | None = Field(..., alias="completedAt")


class Result(ApiModel):
    id: str
    job_id: str = Field(..., alias="jobId")
    summary: Any = None
    file_size: float | None = Field(..., alias="fileSize")
    created_at: AwareDatetime = Field(..., alias="createdAt")


class Deleted(ApiModel):
    deleted: Literal[True]


class Cancelled(ApiModel):
    cancelled: Literal[True]


class Symmetry(StrEnum):
    none = "none"
    axisymmetric = "axisymmetric"


class Vertice(ApiModel):
    id: str
    position: list[Any]


class Edge(ApiModel):
    id: str
    v0: str
    v1: str
    face_ids: list[str] | None = Field([], alias="faceIds")


class Face(ApiModel):
    id: str
    vertex_ids: list[str] = Field(..., alias="vertexIds", min_length=2)
    edge_ids: list[str] = Field(..., alias="edgeIds")


class BoundingBox(ApiModel):
    size: list[Any]
    voltage: float


class Group(ApiModel):
    id: str
    name: str
    color: str
    voltage: float | None
    face_ids: list[str] | None = Field([], alias="faceIds")
    edge_ids: list[str] | None = Field([], alias="edgeIds")


class SerializedGeometry(ApiModel):
    version: Literal[1]
    units: Literal["m"]
    symmetry: Symmetry | None = "none"
    vertices: list[Vertice]
    edges: list[Edge]
    faces: list[Face]
    bounding_box: BoundingBox = Field(..., alias="boundingBox")
    groups: list[Group]
    group_order: list[str] = Field(..., alias="groupOrder")


class BeamParams(ApiModel):
    position: list[Any]
    direction: list[Any] | None = None
    e_nominal: confloat(ge=0.0) | None = Field(50, alias="E_nominal")
    d_e_fwhm: confloat(ge=0.0) | None = Field(0, alias="dE_fwhm")
    angle_fwhm_deg: confloat(ge=0.0) | None = 0
    mass_amu: confloat(ge=0.0) | None = 1
    charge_number: conint(ge=0) | None = 1
    n_particles: conint(ge=0) | None = 100
    seed: int | None = 42


class SolverType(StrEnum):
    fd = "fd"
    fd_3d = "fd_3d"
    bem_2d = "bem_2d"
    bem_3d = "bem_3d"
    bem_axisym = "bem_axisym"
    hybrid = "hybrid"


class Method(StrEnum):
    direct = "direct"
    cg = "cg"
    sor = "sor"


class SolverParams(ApiModel):
    solver_type: SolverType
    method: Method | None = None


class IntegratorParams(ApiModel):
    dt_init: confloat(ge=0.0) | None = 1e-12
    dt_min: confloat(ge=0.0) | None = 1e-16
    dt_max: confloat(ge=0.0) | None = 1e-09
    rtol: confloat(ge=0.0) | None = 1e-09
    atol: confloat(ge=0.0) | None = 1e-15
    max_steps: conint(ge=0) | None = 20000
    t_max: confloat(ge=0.0) | None = 1e-06


class ExitPlane(StrEnum):
    y_cross_zero = "y_cross_zero"
    y_cross_positive = "y_cross_positive"


class EnsembleParams(ApiModel):
    exit_plane: ExitPlane
    slit_centre: float | None = None
    slit_half_width: float | None = None
    store_trajectories: bool | None = False


class SpaceChargeParams(ApiModel):
    beam_current: confloat(ge=0.0)
    r_max: confloat(ge=0.0)
    z_min: float
    z_max: float
    nr: conint(ge=0)
    nz: conint(ge=0)
    max_iter: conint(ge=0) | None = 20
    tol: confloat(ge=0.0) | None = 0.001


class Coils(ApiModel):
    centre: list[Any]
    axis: list[Any]
    r: confloat(ge=0.0) = Field(..., alias="R")
    i: float = Field(..., alias="I")
    type: Literal["circular_loop"]


class Coils1(ApiModel):
    centre: list[Any]
    axis: list[Any]
    r: confloat(ge=0.0) = Field(..., alias="R")
    i: float = Field(..., alias="I")
    type: Literal["solenoid"]
    n: conint(ge=0) = Field(..., alias="N")
    length: confloat(ge=0.0)


class Coils2(ApiModel):
    centre: list[Any]
    axis: list[Any]
    r: confloat(ge=0.0) = Field(..., alias="R")
    i: float = Field(..., alias="I")
    type: Literal["helmholtz"]
    spacing: confloat(ge=0.0)


class MagneticFieldParams(ApiModel):
    coils: list[Coils | Coils1 | Coils2]


class Axe(ApiModel):
    param: str
    values: list[float] = Field(..., min_length=1)


class Strategy(StrEnum):
    grid = "grid"


class ParameterSpace(ApiModel):
    axes: list[Axe] = Field(..., max_length=4, min_length=1)
    strategy: Strategy | None = "grid"


class CreateProjectRequest(ApiModel):
    name: constr(min_length=1, max_length=200)
    description: constr(max_length=2000) | None = None


class ListProjectsResponse(ApiModel):
    items: list[Project]
    total: int


class UpdateProjectRequest(ApiModel):
    name: constr(min_length=1, max_length=200) | None = None
    description: constr(max_length=2000) | None = None


class DeleteProjectRequest(ApiModel):
    pass


class CreateGeometryRequest(ApiModel):
    project_id: str = Field(..., alias="projectId")
    name: constr(min_length=1, max_length=200)
    description: constr(max_length=2000) | None = None
    geometry_data: SerializedGeometry = Field(..., alias="geometryData")


class ListGeometriesResponse(ApiModel):
    items: list[GeometryListItem]
    total: int


class GetGeometryResponse(ApiModel):
    id: str
    org_id: str = Field(..., alias="orgId")
    created_by: str = Field(..., alias="createdBy")
    project_id: str = Field(..., alias="projectId")
    name: str
    description: str | None
    size_bytes: float = Field(..., alias="sizeBytes")
    vertex_count: int = Field(..., alias="vertexCount")
    face_count: int = Field(..., alias="faceCount")
    group_count: int = Field(..., alias="groupCount")
    thumbnail_url: str | None = Field(..., alias="thumbnailUrl")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")
    geometry_data: SerializedGeometry = Field(..., alias="geometryData")


class UpdateGeometryRequest(ApiModel):
    name: constr(min_length=1, max_length=200) | None = None
    description: constr(max_length=2000) | None = None
    geometry_data: SerializedGeometry | None = Field(None, alias="geometryData")


class DeleteGeometryRequest(ApiModel):
    pass


class SimulatorType(StrEnum):
    ion_optics = "ion_optics"


class ListSimulationsResponse(ApiModel):
    items: list[Simulation]
    total: int


class DeleteSimulationRequest(ApiModel):
    pass


class ListSimulationTemplatesResponse(ApiModel):
    items: list[Simulation]


class CloneSimulationRequest(ApiModel):
    template_id: str = Field(..., alias="templateId")
    project_id: str = Field(..., alias="projectId")
    name: constr(min_length=1, max_length=200)
    description: constr(max_length=2000) | None = None


class ListSimulationJobsResponse(ApiModel):
    items: list[Job]
    total: int


class ListJobsResponse(ApiModel):
    items: list[Job]
    total: int


class CancelJobRequest(ApiModel):
    pass


class CreateSimulationSweepRequest(ApiModel):
    name: constr(min_length=1, max_length=200)
    parameter_space: ParameterSpace = Field(..., alias="parameterSpace")


class ListSimulationSweepsResponse(ApiModel):
    items: list[Sweep]
    total: int


class CancelSweepRequest(ApiModel):
    pass


class ListJobResultsResponse(ApiModel):
    items: list[Result]
    total: int


class DownloadJobResultResponse(ApiModel):
    url: str


class PresignUploadRequest(ApiModel):
    filename: constr(min_length=1, max_length=255)
    content_type: constr(min_length=1, max_length=100) = Field(..., alias="contentType")


class PresignUploadResponse(ApiModel):
    url: str
    key: str


class SimulationParams(ApiModel):
    solver: SolverParams | None = None
    beam: BeamParams | None = None
    integrator: IntegratorParams | None = None
    ensemble: EnsembleParams | None = None
    space_charge: SpaceChargeParams | None = Field(None, alias="spaceCharge")
    magnetic_field: MagneticFieldParams | None = Field(None, alias="magneticField")


class CreateSimulationRequest(ApiModel):
    project_id: str = Field(..., alias="projectId")
    name: constr(min_length=1, max_length=200)
    description: constr(max_length=2000) | None = None
    simulator_type: SimulatorType | None = Field("ion_optics", alias="simulatorType")
    geometry_id: str | None = Field(None, alias="geometryId")
    params: SimulationParams | None = None
    is_template: bool | None = Field(False, alias="isTemplate")


class UpdateSimulationRequest(ApiModel):
    name: constr(min_length=1, max_length=200) | None = None
    description: constr(max_length=2000) | None = None
    geometry_id: str | None = Field(None, alias="geometryId")
    params: SimulationParams | None = None


class CreateSimulationJobRequest(ApiModel):
    name: constr(min_length=1, max_length=200) | None = None
    params: SimulationParams | None = None
