# generated by datamodel-codegen:
#   filename:  openapi-filtered.json
#   timestamp: 2026-07-16T13:10:37+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, Field, RootModel

from ionforge._types._base_model import ApiModel


class Project(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    created_by: Annotated[str, Field(alias="createdBy")]
    name: str
    description: str | None
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class ProjectWithCounts(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    created_by: Annotated[str, Field(alias="createdBy")]
    name: str
    description: str | None
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]
    model_count: Annotated[
        int, Field(alias="modelCount", ge=-9007199254740991, le=9007199254740991)
    ]
    geometry_count: Annotated[
        int, Field(alias="geometryCount", ge=-9007199254740991, le=9007199254740991)
    ]


class GeometryMeta(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    created_by: Annotated[str, Field(alias="createdBy")]
    project_id: Annotated[str | None, Field(alias="projectId")]
    name: str
    description: str | None
    size_bytes: Annotated[float, Field(alias="sizeBytes")]
    vertex_count: Annotated[
        int, Field(alias="vertexCount", ge=-9007199254740991, le=9007199254740991)
    ]
    face_count: Annotated[
        int, Field(alias="faceCount", ge=-9007199254740991, le=9007199254740991)
    ]
    group_count: Annotated[
        int, Field(alias="groupCount", ge=-9007199254740991, le=9007199254740991)
    ]
    thumbnail_url: Annotated[str | None, Field(alias="thumbnailUrl")]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class GeometryListItem(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    created_by: Annotated[str, Field(alias="createdBy")]
    name: str
    description: str | None
    thumbnail_url: Annotated[str | None, Field(alias="thumbnailUrl")]
    vertex_count: Annotated[
        int, Field(alias="vertexCount", ge=-9007199254740991, le=9007199254740991)
    ]
    face_count: Annotated[
        int, Field(alias="faceCount", ge=-9007199254740991, le=9007199254740991)
    ]
    group_count: Annotated[
        int, Field(alias="groupCount", ge=-9007199254740991, le=9007199254740991)
    ]
    size_bytes: Annotated[float, Field(alias="sizeBytes")]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class ObjectiveDirection(StrEnum):
    maximize = "maximize"
    minimize = "minimize"


class Model(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    user_id: Annotated[str, Field(alias="userId")]
    project_id: Annotated[str | None, Field(alias="projectId")]
    name: str
    description: str | None
    simulator_type: Annotated[str, Field(alias="simulatorType")]
    geometry_id: Annotated[str | None, Field(alias="geometryId")]
    params: Any | None = None
    is_template: Annotated[bool, Field(alias="isTemplate")]
    objective_metric: Annotated[str | None, Field(alias="objectiveMetric")]
    objective_direction: Annotated[
        ObjectiveDirection | None, Field(alias="objectiveDirection")
    ]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class ModelWithCounts(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    user_id: Annotated[str, Field(alias="userId")]
    project_id: Annotated[str | None, Field(alias="projectId")]
    name: str
    description: str | None
    simulator_type: Annotated[str, Field(alias="simulatorType")]
    geometry_id: Annotated[str | None, Field(alias="geometryId")]
    params: Any | None = None
    is_template: Annotated[bool, Field(alias="isTemplate")]
    objective_metric: Annotated[str | None, Field(alias="objectiveMetric")]
    objective_direction: Annotated[
        ObjectiveDirection | None, Field(alias="objectiveDirection")
    ]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]
    run_count: Annotated[
        int, Field(alias="runCount", ge=-9007199254740991, le=9007199254740991)
    ]
    latest_run_status: Annotated[str | None, Field(alias="latestRunStatus")]


class Run(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    user_id: Annotated[str, Field(alias="userId")]
    model_id: Annotated[str, Field(alias="modelId")]
    name: str
    status: str
    simulator_type: Annotated[str, Field(alias="simulatorType")]
    geometry_id: Annotated[str | None, Field(alias="geometryId")]
    params: Any | None = None
    sweep_id: Annotated[str | None, Field(alias="sweepId")]
    sweep_point: Annotated[Any, Field(alias="sweepPoint")] = None
    error_message: Annotated[str | None, Field(alias="errorMessage")]
    error_message_raw: Annotated[str | None, Field(alias="errorMessageRaw")]
    error_code: Annotated[str | None, Field(alias="errorCode")]
    trace_id: Annotated[str | None, Field(alias="traceId")]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    started_at: Annotated[AwareDatetime | None, Field(alias="startedAt")]
    completed_at: Annotated[AwareDatetime | None, Field(alias="completedAt")]


class TotalPoints(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Phase(StrEnum):
    before_solve = "before_solve"
    solving = "solving"
    in_loop = "in_loop"


class PointsCompletedAtRequestTime(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Sweep(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    user_id: Annotated[str, Field(alias="userId")]
    model_id: Annotated[str, Field(alias="modelId")]
    name: str
    status: str
    strategy: str
    parameter_space: Annotated[Any | None, Field(alias="parameterSpace")] = None
    axes: Any | None = None
    total_points: Annotated[TotalPoints | None, Field(alias="totalPoints")]
    completed_points: Annotated[
        int, Field(alias="completedPoints", ge=-9007199254740991, le=9007199254740991)
    ]
    objective_metric: Annotated[str | None, Field(alias="objectiveMetric")]
    objective_direction: Annotated[
        ObjectiveDirection | None, Field(alias="objectiveDirection")
    ]
    best_run_id: Annotated[str | None, Field(alias="bestRunId")]
    best_settled_at: Annotated[AwareDatetime | None, Field(alias="bestSettledAt")]
    parent_sweep_id: Annotated[str | None, Field(alias="parentSweepId")]
    phase: Phase | None = None
    points_completed_at_request_time: Annotated[
        PointsCompletedAtRequestTime | None, Field(alias="pointsCompletedAtRequestTime")
    ] = None
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    started_at: Annotated[AwareDatetime | None, Field(alias="startedAt")]
    completed_at: Annotated[AwareDatetime | None, Field(alias="completedAt")]


class Result(ApiModel):
    id: str
    run_id: Annotated[str, Field(alias="runId")]
    summary: Any = None
    solver_meta: Annotated[Any, Field(alias="solverMeta")] = None
    file_size: Annotated[float | None, Field(alias="fileSize")]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]


class Deleted(ApiModel):
    deleted: Literal[True]


class Symmetry(StrEnum):
    none = "none"
    axisymmetric = "axisymmetric"
    planar = "planar"


class Vertice(ApiModel):
    id: str
    position: list[Any]


class Edge(ApiModel):
    id: str
    v0: str
    v1: str
    face_ids: Annotated[list[str] | None, Field(alias="faceIds")] = []


class Face(ApiModel):
    id: str
    vertex_ids: Annotated[list[str], Field(alias="vertexIds")]
    edge_ids: Annotated[list[str], Field(alias="edgeIds")]


class BoundingBox(ApiModel):
    size: list[Any]
    voltage: float


class Group(ApiModel):
    id: str
    name: str
    color: str
    voltage: float | None
    face_ids: Annotated[list[str] | None, Field(alias="faceIds")] = []
    edge_ids: Annotated[list[str] | None, Field(alias="edgeIds")] = []


class ImportSource(ApiModel):
    kind: Literal["stl"]
    mode: Literal["run_only"]
    filename: Annotated[str, Field(min_length=1)]
    unit_scale_meters: Annotated[float, Field(alias="unitScaleMeters", gt=0.0)]
    component_count: Annotated[
        int,
        Field(alias="componentCount", ge=-9007199254740991, gt=0, le=9007199254740991),
    ]


class SerializedGeometry(ApiModel):
    version: Literal[1]
    units: Literal["m"]
    symmetry: Symmetry | None = Symmetry.none
    vertices: list[Vertice]
    edges: list[Edge]
    faces: list[Face]
    bounding_box: Annotated[BoundingBox, Field(alias="boundingBox")]
    groups: list[Group]
    group_order: Annotated[list[str], Field(alias="groupOrder")]
    import_source: Annotated[ImportSource | None, Field(alias="importSource")] = None


class MirrorMode(StrEnum):
    none = "none"
    mirror = "mirror"
    biaxial = "biaxial"


class Symmetry1(ApiModel):
    mirror_mode: Annotated[MirrorMode | None, Field(alias="mirrorMode")] = (
        MirrorMode.none
    )


class Electrode(ApiModel):
    name: Annotated[str, Field(min_length=1)]
    voltage: float
    group: Annotated[str | None, Field(min_length=1)] = None
    mask_key: Annotated[str | None, Field(min_length=1)] = None


class FastAdjust(ApiModel):
    enabled: bool | None = False
    gpu: bool | None = False
    electrodes: Annotated[list[Electrode] | None, Field(default_factory=list)]
    parent_run_id: Annotated[str | None, Field(min_length=1)] = None


class Drag(ApiModel):
    drag_coeff: Annotated[float, Field(gt=0.0)]


class RfDrive(ApiModel):
    electrode: Annotated[str, Field(min_length=1)]
    v_dc: Annotated[float, Field(alias="V_dc")]
    v_rf: Annotated[float, Field(alias="V_rf")]
    omega: Annotated[float, Field(gt=0.0)]
    phase: float | None = 0


class RadialAperture(ApiModel):
    r_max: Annotated[float, Field(gt=0.0)]
    z_min: float
    z_max: float


class Callbacks(ApiModel):
    drag: Drag | None = None
    rf_drives: Annotated[list[RfDrive] | None, Field(default_factory=list)]
    radial_aperture: RadialAperture | None = None


class BeamParams(ApiModel):
    position: list[Any] | None = [-0.05, 0]
    direction: list[Any] | None = None
    e_nominal: Annotated[float | None, Field(alias="E_nominal", ge=0.0)] = 50
    d_e_fwhm: Annotated[float | None, Field(alias="dE_fwhm", ge=0.0)] = 0
    angle_fwhm_deg: Annotated[float | None, Field(ge=0.0)] = 0
    mass_amu: Annotated[float | None, Field(gt=0.0)] = 1
    charge_number: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = 1
    n_particles: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = 100
    seed: Annotated[int | None, Field(ge=-9007199254740991, le=9007199254740991)] = 42


class SolverType(StrEnum):
    fd = "fd"
    fd_3d = "fd_3d"
    bem_2d = "bem_2d"
    bem_3d = "bem_3d"
    bem_axisym = "bem_axisym"
    hybrid = "hybrid"


class Method(StrEnum):
    direct = "direct"
    cg = "cg"
    sor = "sor"


class Resolution(ApiModel):
    n_segments: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    quadrature_order: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    rtol: Annotated[float | None, Field(gt=0.0)] = None
    max_iter: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    nr: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    nz: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    nx: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    ny: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = None
    z_max: float | None = None


class SolverParams(ApiModel):
    solver_type: SolverType
    method: Method | None = None
    resolution: Resolution | None = None


class IntegratorParams(ApiModel):
    dt_init: Annotated[float | None, Field(gt=0.0)] = 1e-12
    dt_min: Annotated[float | None, Field(gt=0.0)] = 1e-16
    dt_max: Annotated[float | None, Field(gt=0.0)] = 1e-09
    rtol: Annotated[float | None, Field(gt=0.0)] = 1e-09
    atol: Annotated[float | None, Field(gt=0.0)] = 1e-15
    max_steps: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = 20000
    t_max: Annotated[float | None, Field(gt=0.0)] = 1e-06
    store_every: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = 10
    use_gpu: bool | None = False


class ExitPlane(StrEnum):
    y_cross_zero = "y_cross_zero"
    y_cross_positive = "y_cross_positive"


class EnsembleParams(ApiModel):
    exit_plane: ExitPlane
    slit_centre: float | None = None
    slit_half_width: float | None = None
    store_trajectories: bool | None = False


class SpaceChargeParams(ApiModel):
    beam_current: Annotated[float, Field(gt=0.0)]
    r_max: Annotated[float, Field(gt=0.0)]
    z_min: float
    z_max: float
    nr: Annotated[int, Field(ge=-9007199254740991, gt=0, le=9007199254740991)]
    nz: Annotated[int, Field(ge=-9007199254740991, gt=0, le=9007199254740991)]
    max_iter: Annotated[
        int | None, Field(ge=-9007199254740991, gt=0, le=9007199254740991)
    ] = 20
    tol: Annotated[float | None, Field(gt=0.0)] = 0.001


class Coils(ApiModel):
    centre: list[Any]
    axis: list[Any]
    r: Annotated[float, Field(alias="R", gt=0.0)]
    i: Annotated[float, Field(alias="I")]
    type: Literal["circular_loop"]


class Coils1(ApiModel):
    centre: list[Any]
    axis: list[Any]
    r: Annotated[float, Field(alias="R", gt=0.0)]
    i: Annotated[float, Field(alias="I")]
    type: Literal["solenoid"]
    n: Annotated[int, Field(alias="N", ge=-9007199254740991, gt=0, le=9007199254740991)]
    length: Annotated[float, Field(gt=0.0)]


class Coils2(ApiModel):
    centre: list[Any]
    axis: list[Any]
    r: Annotated[float, Field(alias="R", gt=0.0)]
    i: Annotated[float, Field(alias="I")]
    type: Literal["helmholtz"]
    spacing: Annotated[float, Field(gt=0.0)]


class MagneticFieldParams(ApiModel):
    coils: list[Coils | Coils1 | Coils2]


class CreateProjectRequest(ApiModel):
    name: Annotated[str, Field(max_length=200, min_length=1)]
    description: Annotated[str | None, Field(max_length=2000)] = None


class ListProjectsResponse(ApiModel):
    items: list[Project]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class UpdateProjectRequest(ApiModel):
    name: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    description: Annotated[str | None, Field(max_length=2000)] = None


class DeleteProjectRequest(ApiModel):
    pass


class CreateGeometryRequest(ApiModel):
    project_id: Annotated[str, Field(alias="projectId")]
    name: Annotated[str, Field(max_length=200, min_length=1)]
    description: Annotated[str | None, Field(max_length=2000)] = None
    geometry_data: Annotated[SerializedGeometry, Field(alias="geometryData")]


class ListGeometriesResponse(ApiModel):
    items: list[GeometryListItem]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class GetGeometryResponse(ApiModel):
    id: str
    org_id: Annotated[str, Field(alias="orgId")]
    created_by: Annotated[str, Field(alias="createdBy")]
    project_id: Annotated[str | None, Field(alias="projectId")]
    name: str
    description: str | None
    size_bytes: Annotated[float, Field(alias="sizeBytes")]
    vertex_count: Annotated[
        int, Field(alias="vertexCount", ge=-9007199254740991, le=9007199254740991)
    ]
    face_count: Annotated[
        int, Field(alias="faceCount", ge=-9007199254740991, le=9007199254740991)
    ]
    group_count: Annotated[
        int, Field(alias="groupCount", ge=-9007199254740991, le=9007199254740991)
    ]
    thumbnail_url: Annotated[str | None, Field(alias="thumbnailUrl")]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]
    geometry_data: Annotated[SerializedGeometry, Field(alias="geometryData")]


class UpdateGeometryRequest(ApiModel):
    name: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    description: Annotated[str | None, Field(max_length=2000)] = None
    geometry_data: Annotated[SerializedGeometry | None, Field(alias="geometryData")] = (
        None
    )
    model_id: Annotated[str | None, Field(alias="modelId")] = None


class DeleteGeometryRequest(ApiModel):
    pass


class SimulatorType(StrEnum):
    ion_optics = "ion_optics"


class ListModelsResponse(ApiModel):
    items: list[Model]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class DeleteModelRequest(ApiModel):
    pass


class ListModelTemplatesResponse(ApiModel):
    items: list[Model]


class CloneModelRequest(ApiModel):
    template_id: Annotated[str, Field(alias="templateId")]
    project_id: Annotated[str, Field(alias="projectId")]
    name: Annotated[str, Field(max_length=200, min_length=1)]
    description: Annotated[str | None, Field(max_length=2000)] = None


class Status(StrEnum):
    queued = "queued"
    running = "running"
    completed = "completed"
    failed = "failed"


class ListModelRunsResponse(ApiModel):
    items: list[Run]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Kind(StrEnum):
    simulate = "simulate"
    solve = "solve"
    run_bundle = "run_bundle"


class ListRunsResponse(ApiModel):
    items: list[Run]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class CancelRunRequest(ApiModel):
    pass


class Range(ApiModel):
    type: Literal["values"]
    values: Annotated[list[float | str], Field(min_length=1)]


class Scale(StrEnum):
    linear = "linear"
    log = "log"


class Range1(ApiModel):
    type: Literal["range"]
    min: float
    max: float
    steps: Annotated[int, Field(ge=2, le=1000)]
    scale: Scale | None = None


class Axes(ApiModel):
    kind: Literal["param"]
    path: Annotated[str, Field(min_length=1)]
    range: Range | Range1


class Range2(ApiModel):
    type: Literal["values"]
    values: Annotated[list[float | str], Field(min_length=1)]


class Range3(ApiModel):
    type: Literal["range"]
    min: float
    max: float
    steps: Annotated[int, Field(ge=2, le=1000)]
    scale: Scale | None = None


class Axes1(ApiModel):
    kind: Literal["geometry"]
    path: Annotated[str, Field(min_length=1)]
    range: Range2 | Range3


class Strategy(StrEnum):
    grid = "grid"
    random = "random"


class ObjectiveMetric(StrEnum):
    transmission = "transmission"
    energy_resolution_fwhm_ev = "energy_resolution_fwhm_ev"
    psf_fwhm_m = "psf_fwhm_m"
    mean_flight_time_s = "mean_flight_time_s"
    mean_exit_energy_ev = "mean_exit_energy_ev"
    resolving_power_e_over_delta_e = "resolving_power_e_over_delta_e"


class CreateModelSweepRequest(ApiModel):
    name: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    axes: Annotated[list[Axes | Axes1], Field(min_length=1)]
    strategy: Strategy | None = Strategy.grid
    random_count: Annotated[
        int | None,
        Field(alias="randomCount", ge=-9007199254740991, gt=0, le=9007199254740991),
    ] = None
    objective_metric: Annotated[
        ObjectiveMetric | None, Field(alias="objectiveMetric")
    ] = None
    objective_direction: Annotated[
        ObjectiveDirection | None, Field(alias="objectiveDirection")
    ] = None
    parent_sweep_id: Annotated[str | None, Field(alias="parentSweepId")] = None


class ListSweepsResponse(ApiModel):
    items: list[Sweep]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class CancelSweepRequest(ApiModel):
    pass


class CancelRequested(ApiModel):
    sweep_id: Annotated[str, Field(alias="sweepId")]
    requested_at: Annotated[AwareDatetime, Field(alias="requestedAt")]
    points_completed_at_request_time: Annotated[
        PointsCompletedAtRequestTime | None, Field(alias="pointsCompletedAtRequestTime")
    ]
    note: str


class CancelSweepResponse(ApiModel):
    cancel_requested: Annotated[CancelRequested, Field(alias="cancelRequested")]


class Mode(StrEnum):
    table = "table"
    full = "full"


class Row(ApiModel):
    run_id: Annotated[str | None, Field(alias="runId")]
    sweep_point: Annotated[Any | None, Field(alias="sweepPoint")] = None
    status: str
    objective: float | None
    completed_at: Annotated[AwareDatetime | None, Field(alias="completedAt")]
    duration_seconds: Annotated[float | None, Field(alias="durationSeconds")]
    error: str | None


class ListSweepResultsResponse1(ApiModel):
    mode: Literal["table"]
    rows: list[Row]
    next_cursor: Annotated[str | None, Field(alias="nextCursor")]
    total_count: Annotated[
        int, Field(alias="totalCount", ge=-9007199254740991, le=9007199254740991)
    ]


class Row1(ApiModel):
    run_id: Annotated[str | None, Field(alias="runId")]
    sweep_point: Annotated[Any | None, Field(alias="sweepPoint")] = None
    status: str
    objective: float | None
    completed_at: Annotated[AwareDatetime | None, Field(alias="completedAt")]
    duration_seconds: Annotated[float | None, Field(alias="durationSeconds")]
    error: str | None
    result_summary: Annotated[Any, Field(alias="resultSummary")] = None


class ListSweepResultsResponse2(ApiModel):
    mode: Literal["full"]
    rows: list[Row1]
    next_cursor: Annotated[str | None, Field(alias="nextCursor")]
    total_count: Annotated[
        int, Field(alias="totalCount", ge=-9007199254740991, le=9007199254740991)
    ]


class ListSweepResultsResponse(
    RootModel[ListSweepResultsResponse1 | ListSweepResultsResponse2]
):
    root: ListSweepResultsResponse1 | ListSweepResultsResponse2


class Kind1(StrEnum):
    grid = "grid"
    random = "random"


class Best(ApiModel):
    run_id: Annotated[str, Field(alias="runId")]
    sweep_point: Annotated[Any | None, Field(alias="sweepPoint")] = None
    objective: float
    result_summary: Annotated[Any, Field(alias="resultSummary")] = None
    settled_at: Annotated[AwareDatetime, Field(alias="settledAt")]
    is_final: Annotated[bool, Field(alias="isFinal")]


class Point(ApiModel):
    coords: Any | None = None
    objective: float | None
    status: str


class Surface(ApiModel):
    axes: Any | None = None
    points: list[Point]


class Stats(ApiModel):
    total_points: Annotated[TotalPoints | None, Field(alias="totalPoints")]
    completed_points: Annotated[
        int, Field(alias="completedPoints", ge=-9007199254740991, le=9007199254740991)
    ]
    failed_points: Annotated[
        int, Field(alias="failedPoints", ge=-9007199254740991, le=9007199254740991)
    ]
    cancelled_points: Annotated[
        int, Field(alias="cancelledPoints", ge=-9007199254740991, le=9007199254740991)
    ]
    failure_rate: Annotated[float, Field(alias="failureRate")]
    is_degraded: Annotated[bool, Field(alias="isDegraded")]


class GetSweepAggregateResponse(ApiModel):
    kind: Kind1
    best: Best | None
    surface: Surface | None
    stats: Stats


class ListRunResultsResponse(ApiModel):
    items: list[Result]
    total: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class DownloadRunResultResponse(ApiModel):
    url: str


class DownloadRunResultVizResponse(ApiModel):
    data: str


class PresignUploadRequest(ApiModel):
    filename: Annotated[str, Field(max_length=255, min_length=1)]
    content_type: Annotated[
        str, Field(alias="contentType", max_length=100, min_length=1)
    ]


class PresignUploadResponse(ApiModel):
    url: str
    key: str


class ModelParams(ApiModel):
    solver: SolverParams | None = None
    beam: BeamParams | None = None
    integrator: IntegratorParams | None = None
    ensemble: EnsembleParams | None = None
    space_charge: Annotated[SpaceChargeParams | None, Field(alias="spaceCharge")] = None
    magnetic_field: Annotated[
        MagneticFieldParams | None, Field(alias="magneticField")
    ] = None
    symmetry: Symmetry1 | None = None
    fast_adjust: FastAdjust | None = None
    callbacks: Callbacks | None = None


class CreateModelRequest(ApiModel):
    project_id: Annotated[str, Field(alias="projectId")]
    name: Annotated[str, Field(max_length=200, min_length=1)]
    description: Annotated[str | None, Field(max_length=2000)] = None
    simulator_type: Annotated[SimulatorType | None, Field(alias="simulatorType")] = (
        SimulatorType.ion_optics
    )
    geometry_id: Annotated[str | None, Field(alias="geometryId")] = None
    params: ModelParams | None = None
    is_template: Annotated[bool | None, Field(alias="isTemplate")] = False


class UpdateModelRequest(ApiModel):
    name: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    description: Annotated[str | None, Field(max_length=2000)] = None
    geometry_id: Annotated[str | None, Field(alias="geometryId")] = None
    params: ModelParams | None = None


class CreateModelRunRequest(ApiModel):
    name: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    params: ModelParams | None = None
    kind: Kind | None = None
    parent_run_id: Annotated[str | None, Field(alias="parentRunId")] = None
